function createfigure_pr(X1, Y1, X2, Y2, X3, Y3, X4, Y4)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3, X4, Y4)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  X4:  vector of x data
%  Y4:  vector of y data

%  Auto-generated by MATLAB on 05-Jun-2018 07:04:28

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','JDA','Marker','square','LineWidth',2);

% Create plot
plot(X2,Y2,'DisplayName','NN','Marker','x','LineWidth',2,'Color',[1 0 0]);

% Create plot
plot(X3,Y3,'DisplayName','Subspace','Marker','o','LineWidth',2,...
    'Color',[0 1 0]);

% Create plot
plot(X4,Y4,'DisplayName','Bayesian','Marker','diamond','LineWidth',2,...
    'Color',[0 0 0]);

% Create xlabel
xlabel('Recall');

% Create ylabel
ylabel('Precision');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',20);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.241186261298284 0.38501515442143 0.0675595238095238 0.131239935587762],...
    'FontSize',16);

